### PR TITLE
Add property to set a max image size and resize it

### PR DESCRIPTION
**Pull request by hugorezende**
Hello!

Thanks a lot for your work on this project.

I'm using it and after some days in production, we started to face the same problem as related in issue #55. After investigating it for a while, I found out this problem is related to the easy-react-crop and Safari.
There is a limit of memory used for drawing canvas, and several users have related this issue in the [react-easy-crop](https://github.com/ricardo-ch/react-easy-crop):

[https://github.com/ricardo-ch/react-easy-crop/issues/98]
[https://github.com/ricardo-ch/react-easy-crop/issues/91]
[https://github.com/ricardo-ch/react-easy-crop/issues/147]

The only possible solution suggested to get rid of it is resizing the image before.

Since the `beforeCrop()` implemented here does not allow to modify the file, I thought that would be great if we could set a limit of width our height, and adjust resize the file.
To do it, I'm using the Pica, which can deal with the IOS problems nicely.
[https://github.com/nodeca/pica/wiki/iOS-Memory-Limit]

Feel free to make any suggestions in the code or in the approach.

### CODE REVIEW

**Comment by hugorezende** [comment]
Sorry, just realized some problems with this PR.

**Comment by IvesPower** [comment]
@hugorezende , I'm struggling with the same issue for IOS. I've tried to resize the uploaded picture with Pica also in the BeforeCrop method, but it seems I'm not able to modify the Image pass to react-easy-crop component. Have you find a way to fix this bug ?

**Comment by hugorezende** [comment]
@IvesPower I think so. This can be solved by resizing the image before creating the canvas. I suggested adding a feature to set a max limit for the height or width in this #113.

Since @nanxiaobei decided to not add the feature, you could try the forked version that I've published on npm and check if it solves the problem for you:
https://www.npmjs.com/package/@hugorezende/antd-img-crop

If you decide to try, let me know if it has fixed the problem. :)

**Comment by IvesPower** [comment]
Allright I will try your package to see if it finaly solves this issues :) Thank's a lot for sharing 👍

**Comment by IvesPower** [comment]
Fine, I was able to resize the image with your package, then it should work as well on IOS 🥇 

However, I had to assign the uid of the files from the File list. Seems like this property is not well set when using the resizeMaxSize. Any hint for this ? 

I had to update the onChange method of the upload field : 

`const onChange = (values: any) => {
		values.fileList.map((fileFromList:any) => {
			if (!fileFromList.uid){
				fileFromList.uid = uuidv4(); // define a new uid
			}
		});
		setFileList(values.fileList);
	};
`

**Comment by hugorezende** [comment]
Hm, I see... The point is that you're assigning this uid to a type 'any', so it has a different signature from the File type. 
Instead of using a new field 'uid', you can just replace the property name of the file.

 `if (!fileFromList.uid){ fileFromList.name = uuidv4(); // define a new uid }`

**Comment by komarovalexander** [comment]
Hi @hugorezende`resizeMaxSize ` is actually great feature, can you add it to the latest version? 

[@hugorezende/antd-img-crop](https://www.npmjs.com/package/@hugorezende/antd-img-crop) does not work with the latest antd version unfortunatelly

**Pull request closed without merging**
